# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Raffi < Formula
  desc "raffi - fuzzel launcher based on yaml configuration"
  homepage "https://github.com/chmouel/raffi"
  version "0.17.0"
  depends_on :linux

  on_intel do
    if Hardware::CPU.is_64_bit?
      url "https://github.com/chmouel/raffi/releases/download/v0.17.0/raffi_0.17.0_linux_x86_64.tar.gz"
      sha256 "499e9cc2ad0318ad16e84826c2d5106bdac5f093887f78b39e95f36fee70e42f"

      def install
        bin.install "raffi" => "raffi"
        prefix.install_metafiles
      end
    end
  end
end
