# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Raffi < Formula
  desc "raffi - wofi launcher based on yaml configuration"
  homepage "https://github.com/chmouel/raffi"
  version "0.0.1"

  on_macos do
    url "https://github.com/chmouel/raffi/releases/download/v0.0.1/raffi_0.0.1_macOS_all.tar.gz"
    sha256 "bfa2f903dfde81e8b3efb96366e86a4c712d2e2b99303568d70f34ad8cf312e4"

    def install
      bin.install "raffi" => "raffi"
      prefix.install_metafiles

      output = Utils.popen_read("SHELL=bash #{bin}/raffi --shell-completion bash")
      (bash_completion/"raffi").write output

      output = Utils.popen_read("SHELL=zsh #{bin}/raffi --shell-completion zsh")
      (zsh_completion/"_raffi").write output

      output = Utils.popen_read("SHELL=fish #{bin}/raffi --shell-completion fish")
      (fish_completion/"raffi.fish").write output
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chmouel/raffi/releases/download/v0.0.1/raffi_0.0.1_linux_amd64.tar.gz"
      sha256 "02621d0fd14e06ed5c87bbeff8a3e85e01ca413e4be04f28085e4821a4267f98"

      def install
        bin.install "raffi" => "raffi"
        prefix.install_metafiles

        output = Utils.popen_read("SHELL=bash #{bin}/raffi --shell-completion bash")
        (bash_completion/"raffi").write output

        output = Utils.popen_read("SHELL=zsh #{bin}/raffi --shell-completion zsh")
        (zsh_completion/"_raffi").write output

        output = Utils.popen_read("SHELL=fish #{bin}/raffi --shell-completion fish")
        (fish_completion/"raffi.fish").write output
      end
    end
  end
end
